Repository shopgate/theme-gmd, pull requests merged in 2018-09, with the labels that each got.

#401 PWA-910 Finalized the Selector.
  pages/Filter/components/Content/components/Selector/components/Toggle/index.jsx
  pages/Filter/components/Content/components/Selector/components/Toggle/style.js
  pages/Filter/components/Content/components/Selector/components/ValueButton/index.jsx
  pages/Filter/components/Content/components/Selector/components/ValueButton/style.js
  pages/Filter/components/Content/components/Selector/index.jsx
  pages/Filter/components/Content/index.jsx
Labels: enhancement

#403 PWA-913 add portals back to filters
  pages/Filter/components/Content/index.jsx
Labels: enhancement

#406 PWA-922 refactor filter chips
  components/FilterBar/components/Content/components/FilterChips/connector.js
  components/FilterBar/components/Content/components/FilterChips/index.jsx
  components/FilterBar/components/Content/components/FilterChips/style.js
  components/FilterBar/components/Content/index.jsx
  components/FilterBar/index.jsx
  components/FilterBar/style.js
  components/FilterBar/transition.js
  pages/Filter/components/Content/helpers/buildInitialFilters.js
  pages/Filter/components/Content/index.jsx
Labels: enhancement

#408 PWA-945 Updated conductor
  package.json
Labels: enhancement

#405 PWA-875: Implement dynamic redirects
  pages/Login/index.jsx
  pages/subscriptions.js
Labels: bug

#416 PWA-885 Fixed test temporarily.
  e2e/integration/functional/CartPage.js
Labels: bug

#415 PWA-950 Optimized product header.
  pages/Product/components/Header/components/Availability/index.jsx
  pages/Product/components/Header/components/CTAButtons/components/CartButton/components/Icon/index.jsx
  pages/Product/components/Header/components/CTAButtons/components/CartButton/connector.js
  pages/Product/components/Header/components/CTAButtons/connector.js
  pages/Product/components/Header/components/CTAButtons/index.jsx
  pages/Product/components/Header/components/Manufacturer/connector.js
  pages/Product/components/Header/components/Manufacturer/index.jsx
  pages/Product/components/Header/components/Name/index.jsx
  pages/Product/components/Header/components/Price/index.jsx
  pages/Product/components/Header/components/PriceInfo/index.jsx
  pages/Product/components/Header/components/PriceStriked/index.jsx
  pages/Product/components/Header/components/ProductInfo/index.jsx
  pages/Product/components/Header/components/ProductInfo/style.js
  pages/Product/components/Header/components/Rating/__snapshots__/spec.jsx.snap
  pages/Product/components/Header/components/Rating/index.jsx
  pages/Product/components/Header/components/Shipping/__snapshots__/spec.jsx.snap
  pages/Product/components/Header/components/Shipping/index.jsx
  pages/Product/components/Header/components/TaxDisclaimer/index.jsx
  pages/Product/components/Header/components/TaxDisclaimer/style.js
  pages/Product/components/Header/components/Tiers/__snapshots__/spec.jsx.snap
  pages/Product/components/Header/components/Tiers/components/Tier/index.jsx
  pages/Product/components/Header/components/Tiers/index.jsx
  pages/Product/components/Header/index.jsx
  pages/Product/components/Header/style.js
Labels: enhancement

#414 PWA-959 remove redux props
  package.json
  pages/Filter/components/Content/connector.js
  pages/Filter/components/Content/index.jsx
Labels: bug

#417 PWA-953 Optimize characteristics
  pages/Product/components/Characteristics/Characteristic/components/Sheet/index.jsx
  pages/Product/components/Characteristics/Characteristic/components/SheetItem/index.jsx
  pages/Product/components/Characteristics/Characteristic/components/VariantAvailability/connector.js
  pages/Product/components/Characteristics/Characteristic/components/VariantAvailability/index.jsx
  pages/Product/components/Characteristics/Characteristic/index.jsx
  pages/Product/components/Characteristics/index.jsx
Labels: enhancement

#412 PWA-558 optimise nav drawer
  components/NavDrawer/components/CartButton/components/Badge/connector.js
  components/NavDrawer/components/CartButton/components/Badge/index.jsx
  components/NavDrawer/components/CartButton/components/Badge/style.js
  components/NavDrawer/components/CartButton/index.jsx
  components/NavDrawer/components/CartItem/index.jsx
  components/NavDrawer/components/CategoryButton/index.jsx
  components/NavDrawer/components/Divider/index.jsx
  components/NavDrawer/components/Divider/style.js
  components/NavDrawer/components/FavoritesButton/components/Badge/connector.js
  components/NavDrawer/components/FavoritesButton/components/Badge/index.jsx
  components/NavDrawer/components/FavoritesButton/components/Badge/style.js
  components/NavDrawer/components/FavoritesButton/index.jsx
  components/NavDrawer/components/Header/connector.js
  components/NavDrawer/components/Header/index.jsx
  components/NavDrawer/components/Header/style.js
  components/NavDrawer/components/HomeButton/index.jsx
  components/NavDrawer/components/ImprintButton/index.jsx
  components/NavDrawer/components/Item/connector.js
  components/NavDrawer/components/Item/index.jsx
  components/NavDrawer/components/Item/style.js
  components/NavDrawer/components/Layout/index.jsx
  components/NavDrawer/components/Layout/style.js
  components/NavDrawer/components/LogoutButton/connector.js
  components/NavDrawer/components/LogoutButton/index.jsx
  components/NavDrawer/components/PaymentButton/index.jsx
  components/NavDrawer/components/PrivacyButton/index.jsx
  components/NavDrawer/components/QuickLinks/connector.js
  components/NavDrawer/components/QuickLinks/index.jsx
  components/NavDrawer/components/ReturnsButton/index.jsx
  components/NavDrawer/components/ShippingButton/index.jsx
  components/NavDrawer/components/TermsButton/index.jsx
  components/NavDrawer/connector.js
  components/NavDrawer/index.jsx
  components/NavDrawer/selectors.js
  components/Navigator/action-creators/index.js
  components/Navigator/actions.spec.js
  components/Navigator/actions/toggleNavDrawer.js
  components/Navigator/components/NavButton/connector.js
  components/Navigator/components/NavButton/index.jsx
  components/Navigator/constants.js
  components/Navigator/reducer.js
  components/Navigator/selectors/index.js
  locale/en-US.json
  pages/subscriptions.js
Labels: enhancement

#418 PWA-954 Optimized product options.
  components/List/components/Item/style.js
  components/List/style.js
  pages/Product/components/Options/components/Option/index.jsx
  pages/Product/components/Options/components/Option/style.js
  pages/Product/components/Options/connector.js
  pages/Product/components/Options/index.jsx
Labels: enhancement

#419 PWA-955 Optimized product properties.
  pages/Product/components/Properties/components/PropertyRows/index.jsx
  pages/Product/components/Properties/components/PropertyRows/style.js
  pages/Product/components/Properties/index.jsx
  pages/Product/components/Properties/style.js
Labels: enhancement

#423 PWA-957 Optimized Tax Disclaimer.
  components/List/__snapshots__/spec.jsx.snap
  pages/Cart/__snapshots__/spec.jsx.snap
  pages/Cart/components/Footer/__snapshots__/spec.jsx.snap
  pages/Category/__snapshots__/spec.jsx.snap
  pages/Product/components/Content/__snapshots__/spec.jsx.snap
  pages/Product/components/Content/index.jsx
  pages/RootCategory/__snapshots__/spec.jsx.snap
  widgets/CategoryList/__snapshots__/spec.jsx.snap
Labels: enhancement

#422 PWA-956 optimize pdp reviews
  components/Reviews/__snapshots__/spec.jsx.snap
  components/Reviews/components/AllReviewsLink/connector.js
  components/Reviews/components/AllReviewsLink/index.jsx
  components/Reviews/components/AllReviewsLink/style.js
  components/Reviews/components/Header/__snapshots__/spec.jsx.snap
  components/Reviews/components/Header/components/AverageRating/index.jsx
  components/Reviews/components/Header/components/NoReviews/index.jsx
  components/Reviews/components/Header/components/NoReviews/style.js
  components/Reviews/components/Header/components/ReviewsExcerpt/index.jsx
  components/Reviews/components/Header/components/ReviewsExcerpt/style.js
  components/Reviews/components/Header/connector.js
  components/Reviews/components/Header/index.jsx
  components/Reviews/components/Header/spec.jsx
  components/Reviews/components/Header/style.js
  components/Reviews/components/List/__snapshots__/spec.jsx.snap
  components/Reviews/components/List/components/Info/components/Author/index.jsx
  components/Reviews/components/List/components/Info/components/ReviewDate/index.jsx
  components/Reviews/components/List/components/Info/index.jsx
  components/Reviews/components/List/components/Info/style.js
  components/Reviews/components/List/components/Rating/index.jsx
  components/Reviews/components/List/components/Rating/style.js
  components/Reviews/components/List/components/Text/index.jsx
  components/Reviews/components/List/components/Text/style.js
  components/Reviews/components/List/components/Title/index.jsx
  components/Reviews/components/List/components/Title/style.js
  components/Reviews/components/List/index.jsx
  components/Reviews/components/List/spec.jsx
  components/Reviews/components/List/style.js
  components/Reviews/components/RatingCount/index.jsx
  components/Reviews/connector.js
  components/Reviews/index.jsx
  pages/Product/components/Content/__snapshots__/spec.jsx.snap
  pages/Product/components/Content/index.jsx
  pages/Product/components/Header/components/Rating/__snapshots__/spec.jsx.snap
  pages/Reviews/__snapshots__/spec.jsx.snap
  pages/Reviews/components/Content/connector.js
  pages/Reviews/components/Content/index.jsx
  pages/Reviews/spec.jsx
Labels: enhancement

#424 PWA-964 optomize product content
  pages/Product/components/Characteristics/index.jsx
  pages/Product/components/Content/__snapshots__/spec.jsx.snap
  pages/Product/components/Content/index.jsx
  pages/Product/components/Description/__snapshots__/spec.jsx.snap
  pages/Product/components/Description/index.jsx
  pages/Product/components/Header/__snapshots__/spec.jsx.snap
  pages/Product/components/Header/components/Manufacturer/connector.js
  pages/Product/components/Header/index.jsx
  pages/Product/components/ImageSlider/__snapshots__/spec.jsx.snap
  pages/Product/components/ImageSlider/index.jsx
  pages/Product/components/Options/__snapshots__/spec.jsx.snap
  pages/Product/components/Options/index.jsx
  pages/Product/components/Properties/__snapshots__/spec.jsx.snap
  pages/Product/components/Properties/index.jsx
  pages/Product/index.jsx
  pages/Product/spec.jsx
Labels: enhancement

#425 PWA-447 Optimized filter page.
  pages/Filter/components/Content/components/ApplyButton/__snapshots__/spec.jsx.snap
  pages/Filter/components/Content/components/ApplyButton/index.jsx
  pages/Filter/components/Content/components/ApplyButton/spec.jsx
  pages/Filter/components/Content/components/Item/__snapshots__/spec.jsx.snap
  pages/Filter/components/Content/components/Item/spec.jsx
  pages/Filter/components/Content/components/PriceSlider/__snapshots__/spec.jsx.snap
  pages/Filter/components/Content/components/PriceSlider/components/Label/__snapshots__/spec.jsx.snap
  pages/Filter/components/Content/components/PriceSlider/components/Label/index.jsx
  pages/Filter/components/Content/components/PriceSlider/components/Label/spec.jsx
  pages/Filter/components/Content/components/PriceSlider/index.jsx
  pages/Filter/components/Content/components/PriceSlider/spec.jsx
  pages/Filter/components/Content/components/ResetButton/__snapshots__/spec.jsx.snap
  pages/Filter/components/Content/components/ResetButton/index.jsx
  pages/Filter/components/Content/components/ResetButton/spec.jsx
  pages/Filter/components/Content/components/Selector/__snapshots__/spec.jsx.snap
  pages/Filter/components/Content/components/Selector/components/Selected/__snapshots__/spec.jsx.snap
  pages/Filter/components/Content/components/Selector/components/Selected/index.jsx
  pages/Filter/components/Content/components/Selector/components/Selected/spec.jsx
  pages/Filter/components/Content/components/Selector/components/Toggle/index.jsx
  pages/Filter/components/Content/components/Selector/components/ValueButton/index.jsx
  pages/Filter/components/Content/components/Selector/components/ValueButton/style.js
  pages/Filter/components/Content/components/Selector/index.jsx
  pages/Filter/components/Content/components/Selector/spec.jsx
  pages/Filter/components/Content/connector.js
  pages/Filter/components/Content/index.jsx
  pages/Filter/index.jsx
Labels: enhancement

#426 PWA-983 removed description from test id.
  pages/Product/components/Description/__snapshots__/spec.jsx.snap
  pages/Product/components/Description/index.jsx
Labels: enhancement

#437 Reactivated checkout tracking
  pages/Category/components/Bar/__snapshots__/spec.jsx.snap
  pages/Category/components/CategoryListContent/__snapshots__/spec.jsx.snap
  pages/Category/components/Content/__snapshots__/spec.jsx.snap
  pages/Category/components/ProductsContent/__snapshots__/spec.jsx.snap
  pages/subscribers.js
Labels: PR: Bug Fix :bug:

#439 PWA-1025 - hint for an ios10 issue with background-color and overflow…
  components/View/components/Content/style.js
Labels: PR: Polish :nail_care:
